sudo: false

language: ruby

cache: bundler

addons:
  apt:
    packages:
    - bsdtar

rvm:
- 2.3.7
- 2.4.4
- 2.5.0
- 2.5.1

env:
  global:
  - NOKOGIRI_USE_SYSTEM_LIBRARIES=true

script: bundle exec rake test

notifications:
  slack:
    secure: d9jmDMPRbEHfKTmY+FqYNovtDTag+NNBVE2W3YYkGLp4QCGiaHSlV6rCDDmX02fUOtLgA1FrsJJpS17/3sBG6JX3aWh4wIWW8XCzrzUmItWa25J/Fj3KutbJN0pYXeEVDR8Cw0OoAZpzlgBOBbe5mcCpPhHhe3gTUaRBxqCiQII=
